### ISSUE TITLE
Cellplast tre skikt

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#16]
Vi har i dag koder för ett och två skikt med cellplast under platta. Vi saknar tre skikt vilket är standard i dag. Föreslår att vi interpolerar kodvärderna från de två första skikten

**Comment by JFagerdahl** [comment]
Kurvans lutning ska interpoleras från ett och två skikt. 
Presentera förslag på nästa möte.

**Comment by boahlstrand** [comment]
Förslag på ny kod.
Mark -> platta -> isolering -> cellplast -> tre skikt
Rörlig=0,04
Exponent=1
Fast=0,2

Ett skikt   1m2=0,22 mWu   10m2=0,4 mWu
Två skikt  1m2=0,23 mWu   10m2=0,5 mWu
Tre skikt  1m2=0,24 mWu    10m2=0,6 mWu

**Comment by JFagerdahl** [comment]
För release 171111.
