### ISSUE TITLE
Fuktspärrande foam under parkettgolv 

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#20]
Men nu rådande branschrekommendationer lägger byggare in en åldersbeständig och fuktspärrande foam under parkettgolv.
https://www.k-rauta.se/byggvaruhus/tarkoflex-tarkett-ii-underl%C3%A4ggsmatta-2mm-15m%C2%B2
Den kostar mer än traditionell foam och har också självhäftande kanter som innebär en viss ökad arbetsmängd.

MepsFeedback GitHub #223.

**Comment by JFagerdahl** [comment]
Behöver utredas

**Comment by boahlstrand** [comment]
Förslag på ny kod för golvmellanlägg med självhäftande kant.
Golv->stombeklädnad->parkettunderlag->foam->självhäftande mellanlägg
Rörlig=0,05
Exponent=1
Fast=0,1
1m2  -> 8min  (vanlig foam=7 min)
10m2 -> 30min (vanlig foam=20 min)

**Comment by JFagerdahl** [comment]
Beslut på förvaltningsråd 27/9-2017 att  ta in ny kod enligt förslag.

**Comment by JFagerdahl** [comment]
För release 171111.
