### ISSUE TITLE
Gipsplank GKP - Materialval saknas

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#21]
Gipsplank GKP - Materialval saknas i nya Meps 
I gamla Meps fanns Gipsplank GKP. Vilket saknas i nya meps.

Från MepsFeedback GitHub #221.

**Comment by JFagerdahl** [comment]
Bör utredas.

**Comment by boahlstrand** [comment]
Tre olika takgipsskivor är inlagda 2017-09-14
