### ISSUE TITLE
Ny kod för fixtur för vägghängd WC

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#23]
Kod finns för vägghängd WC men inte för tillhörande fixtur.

**Comment by JFagerdahl** [comment]
Tomas Larsson och Bo Ahlstrand har diskuterat hur koden ska se ut. Man har även tittat på monteringsbeskrivningar för att få fram rätt nivå. 
Fixturen har fått 1,25 mWu per styck. 
Spolknapp har egen kod (ny) 0,06 mWu.
Har efterfrågats från entreprenörerna.

**Comment by boahlstrand** [comment]
Nya koder skapade 2017-09-14
