### ISSUE TITLE
X10 kod - nyckelhämtning

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#42]
I Meps regler och Riktlinjer presenterar vi våra x-koder. Där beskriver vi koden "X10 - Nyckelhämtning"
Den finns inte i meps lista över koder.

**Comment by JFagerdahl** [comment]
Utred om koden ska finnas eller om Regler och riktlinjer ska uppdateras.

**Comment by GoranHedlundCAB** [comment]
flyttat till förbätteings githuben

**Comment by JFagerdahl** [comment]
X10 kod ska in i kalkylen. Pratat med Susanne.

**Comment by JFagerdahl** [comment]
Kod för nyckelhämtning finns (19.233.59). Regler och Riktlinjer behöver uppdateras -> X10 tas bort. 
Kommunikatören ska informeras.

**Comment by JFagerdahl** [comment]
X10 – Nyckelhämtning är borttagen från Regler och riktlinjer och publicerat det uppdaterade dokumentet på Behöver du hjälp?-sidan.

**Comment by HenrikBrenkle** [comment]
Denna är klar.
