### ISSUE TITLE
Kunds åsikt om priser 

### ISSUE THREAD

**Issue by GoranHedlundCAB** [Integrationstester/MaintenancePropertyData#43]
Hej
Glömde skriva med att om ni tittar på Beijers prislista så kostar OSB 45krKvm exklusive moms och rabatt. I MEPS borde priset ligger någonstans mellan 40-45kr
Jag har märkt detta på flera materialprodukter vilket inte är ok. Vi betalar en hutlös siffra till er i licenspengar och då förväntar vi oss att ni ska ha aktuella priser i kalkylen så vi itne ska behöva dubbelkolla allt.
 
Ett annat exempel är kök.
Ett skåp med 5 lådor ink handtag mm ersätter ni ca 1.500kr
För 1.500kr får vi inte ens ett skåp på IKEA med handtag mm!?
 
Förslagsvis så tar ni bort licenskostnaden för oss framöver tills ni åtgärdat allt material så att det stämmer med verkligheten och vi inte ska lägga tid på dubbelkolla allt samt betalar tillbaka licensen som vi betalat hittills.

Jonas Erlandsson
Produktionsledare
 
KARATEN BYGG VÄST AB
Nya Tingstadsg. 1, 422 44 Hisings backa
Faktura: faktura.vast@karatenbygg.se
 
Vxl: 010-164 62 00   Tel: 010-164 62 41
E-post: jonas.erlandsson@karatenbygg.se
Webb: www.karatenbygg.se

**Comment by JFagerdahl** [comment]
Generellt så ska synpunkter på materialpriser tas direkt med BoA.
