### ISSUE TITLE
Loss och återinkoppling av vatten till kylskåp

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#44]
Loss och återinkoppling av vatten till kylskåp med ismaskin eller kylt vatten.
Koder för diskmaskin kan återanvändas?

**Comment by HenrikBrenkle** [comment]
Den är klar och kommer med i nästa releas.

**Comment by JFagerdahl** [comment]
Nästa release är 9/12-2017
