### ISSUE TITLE
Översyn av tapetklasser

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#47]
Tapetklasser fanns på 70-80 talet och är ej aktuella längre. Vad ska användas istället? Non-wowen, papperstapet, PVC tapet, mm?

**Comment by HenrikBrenkle** [comment]
Tomas & BoA kommer att gå igenom det i em.

**Comment by JFagerdahl** [comment]
Tomas ska skicka en lista till BoA för att ändra texterna på klass1, 2, osv.

**Comment by JFagerdahl** [comment]
Tapetklasser är ändrade. Kommer till releasen 10/2 -2018.
Behöver inte tas med i release notes.
