### ISSUE TITLE
Vi behöver en ny kod för återmontering av ventilationsfläkt.

### ISSUE THREAD

**Issue by HenrikBrenkle** [Integrationstester/MaintenancePropertyData#48]
Vi behöver en ny kod för återmontering av ventilationsfläkt.
Bör ligga under:  Hushållsmaskiner-Detaljer till hushållsmaskiner-Detaljer till fläkt och spisfläkt-ventilfläkt, Återmontering
Fast=0
Rörlig=0,6
Exponent=1

**Comment by JFagerdahl** [comment]
Ska med i releasen 9/12-2017.
