### ISSUE TITLE
Vi behöver ny kod för ventilationsfläkt i vägg.

### ISSUE THREAD

**Issue by HenrikBrenkle** [Integrationstester/MaintenancePropertyData#49]
Vi behöver ny kod för ventilationsfläkt i vägg.
Föreslår att vi kopierar koderna som ligger under Hushållsmaskiner och lägger dem under:
 EL-El-apparater-Fläkt-Ventilationsfläkt-Fläkt i vägg- Fläkt i vägg,

**Comment by HenrikBrenkle** [comment]
Godkänd och klar. Kommer i nästa release.

**Comment by JFagerdahl** [comment]
Nästa release är 9/12-2017.
