### ISSUE TITLE
Sparning av parkettgolv saknas

### ISSUE THREAD

**Issue by TomasLarssonCAB** [Integrationstester/MaintenancePropertyData#53]
Idag används sparning spånskiva, HE får en del frågor från FB vad dom egentligen gjort

**Comment by JFagerdahl** [comment]
Ny kod ska tas fram med samma värden som för spånskiva. Tas upp på nästa förvaltningsråd.

**Comment by boahlstrand** [comment]
Är utfört!

**Comment by JFagerdahl** [comment]
Kommer till release 10/2-2018.
