### ISSUE TITLE
Nya koder för mjukfog för tak och golv.

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#54]
Mjukfog finns idag på innervägg men saknas för tak och golv. 

Koden Innervägg-lister...-mjukfog....-mjukfog...-löpmeter fog 

kopieras till

Golv-sockel...-mjukfog-löpmeter fog

och

Innertak-taklist-mjukfog-löpmeter fog

**Comment by JFagerdahl** [comment]
Tas upp på nästa förvaltningsråd.

**Comment by boahlstrand** [comment]
Är utfört!

**Comment by JFagerdahl** [comment]
Kommer till release 10/2-2018.
