### ISSUE TITLE
Ny kod. - fler än 4 hål i vägg

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#55]
Saknar kod för fler än 4 hål i vägg för rörgenomföringar.

Innevägg-fuktisolering-tätskit/folie-tätark-rörgenomföring >4st/rum

Värden tas från 
Golv-ytmaterial-detaljer-anslutning mot rör i våtrum >4st/rum
Fast=0
Rörlig=0,2
Exponent=1

**Comment by JFagerdahl** [comment]
Ska implementeras.

**Comment by boahlstrand** [comment]
Utförd!

**Comment by JFagerdahl** [comment]
Kommer till release 10/2-2018.
