### ISSUE TITLE
Nytt material för golvskydd.

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#56]
Nytt material för golvskydd. 
Entreprenörer använder idag ett nytt material för golvskydd som har bättre egenskaper.

https://www.nonwoven.se/bygg/scanocover/

Det kostar mer men är självhäftande och dämpat och vattentätt.

**Comment by JFagerdahl** [comment]
Kan återanvända koder för självhäftande mellanlägg. Tas upp på nästa förvaltningsråd.

**Comment by JFagerdahl** [comment]
@boahlstrand Kolla om denna är genomförd.

**Comment by boahlstrand** [comment]
Ny kod. Självhäftande golvskyddsduk finns under Golv-Skyddning-Golvyta-Med papp/plast-självhäftande golvskyddsduk, Rivning
samt
Ny kod. Självhäftande golvskyddsduk finns under Golv-Skyddning-Golvyta-Med papp/plast-självhäftande golvskyddsduk, Nymontering

Dessa är nu skapade.

**Comment by JFagerdahl** [comment]
Kommer till release 10/2-2018.
