### ISSUE TITLE
Beräkning av arbete och material vid uppvik av golvmatta i våtrum.

### ISSUE THREAD

**Issue by JFagerdahl** [Integrationstester/MaintenancePropertyData#76]
Kunden ifrågasatte om vi räknade med det extra arbetet och materialet?

Meps Support
Namn: Mattias Nilsson
System: MEPS 2
Företag: GolvAB
Ort: Borlänge
Tel: 024313135
E-post: mattias@golvab.se
Ärende: Frågor om MEPS programmet

**Comment by JFagerdahl** [comment]
Det ska ingå men BoA kollar.

**Comment by boahlstrand** [comment]
Kodens materialrecept hade för liten förbrukning av plastmatta. Uppviket fanns inte med.
Jag har nu justerat detta med ett standardbadrum (6 m2) som utgångspunkt. Materialåtgången har justerats från 1 till 1.22 m2 matta per m2 golvyta.
